import Head from 'next/head';
import dynamic from 'next/dynamic';
const ThemeSwitch = dynamic(() => import('./ThemeSwitch'), {
	ssr: false,
});

const Layout = ({ children, title }) => {
	return (
		<>
			<Head>
				<title>
					{title ? `${title} | Amin Charoliya` : 'Amin Charoliya'}
				</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<link rel="icon" href="/favicon.ico" />
			</Head>
			{children}
			<div className="fixed bottom-10 right-10 md:hidden">
				<ThemeSwitch />
			</div>
		</>
	);
};

export default Layout;
